### ISSUE TITLE
Fix CI process to work with external pull requests

### ISSUE THREAD

**Issue by Sharparam** [chroma-sdk/Colore#266]
When a pull request is made from an external repo (see #264 for an example), AppVeyor (rightfully) won't load secrets. This currently causes builds to fail.

Build scripts should be updated to skip anything that requires secrets when building external pull requests.

**Comment by Sharparam** [comment]
Fix is in release branch now.

**Comment by leonardoInf** [comment]
Sorry to bring this up again but errorless pull request aren't possible for me yet:

```
2019-07-13 22:36:47 INF AppVeyor detected.
2019-07-13 22:36:48 INF Git detected.
2019-07-13 22:36:48 INF Project root: C:\projects\colore
2019-07-13 22:36:48 INF Reading reports.
2019-07-13 22:36:48 INF ./artifacts/opencover-results.xml
2019-07-13 22:36:48 INF Uploading Reports.
2019-07-13 22:36:49 INF url: https://codecov.io
2019-07-13 22:36:50 INF query: https://codecov.io/upload/v4?branch=pull%2F267%2Fmerge&commit=8b1fee96ef3251fd640799bfc0b2b6522d6e99b1&build=q18cjilp08ggd0d7&tag=&pr=267&name=&flags=&slug=chroma-sdk%2FColore&token=&package=exe-1.1.1&build_url=&yaml=.codecov.yml&job=chroma-sdk%2Fcolore%2F6.1.0-PullRequest0267.512.build.168-wqswjgdx&service=appveyor
2019-07-13 22:36:50 INF Pinging Codecov
2019-07-13 22:36:53 FTL Failed to upload the report.
   at Codecov.Upload.Uploads.Uploader() in C:\projects\codecov-exe\Source\Codecov\Upload\Uploads.cs:line 34
   at Codecov.Program.UploadFacade.Uploader() in C:\projects\codecov-exe\Source\Codecov\Program\UploadFacade.cs:line 119
   at Codecov.Program.Run.Runner(IEnumerable`1 args) in C:\projects\codecov-exe\Source\Codecov\Program\Run.cs:line 20
Cake.exe : An error occurred when executing task 'Codecov'.
At C:\projects\colore\build.ps1:233 char:1
+ &$CAKE_EXE $cakeArguments
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (An error occurr...task 'Codecov'.:String) [], RemoteException
    + FullyQualifiedErrorId 
```
